### ISSUE TITLE
Release tag?

### ISSUE THREAD

**Issue by kimpepper** [minkphp/MinkGoutteDriver#64] opened 2015-07-14 09:47 UTC
We're trying to pin a version for Drupal 8 (see https://www.drupal.org/node/2493911) which is currently building off master. Is there any chance we can get a tagged release?

**Comment by aik099** [comment] 2015-07-14 09:55
This seems to be a duplicate of #63 issue.

**Comment by stof** [comment] 2015-09-21 21:32
1.2.0 has been released

**Closed by stof** 2015-09-21 21:32 UTC
